#!/usr/bin/python3
import rospy
from std_msgs.msg import Int32
num1 = 0
num2 = 0
def callback1(msg):
    global num1
    num1=msg.data
def callback2(msg1):
    global num2
    num2=msg1.data
def fun():
    rospy.init_node('node5', anonymous=True)
    rospy.Subscriber("topic2", Int32, callback1)
    rospy.Subscriber("topic3", Int32, callback2)
    rate=rospy.Rate(1)
    while not rospy.is_shutdown():
        print("sum is", num1+num2)
        print("sub is", num1-num2)
        rate.sleep()
    rospy.spin()

if __name__ == "__main__":
    fun()
